YakupMyBlog/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YakupMyBlog.Models;

namespace YakupMyBlog.Controllers
{
    public class CategoryController : Controller
    {
        Context context = new Context();
        // GET: Category
        public ActionResult Index(int id)
        {
            return View(id);
        }

        public PartialViewResult CategoryWidget()
        {
            var data = context.Categories.ToList();
            return PartialView(data);
        }

        public ActionResult BlogList(int id)
        {
            var data = context.Blogs.Where(x => x.CategoryID == id).ToList();
            return View("BlogListWidget", data);
        }

        public ActionResult CategoryList()
        {
            var data = context.Categories.ToList();
            return View(data);
        }

        public ActionResult Add()
        {
            Category category = new Category();
            return View(category);
        }

        [HttpPost]
        public ActionResult Add(Category category)
        {
            context.Categories.AddOrUpdate(category);
            context.SaveChanges();
            return RedirectToAction("CategoryList");
        }

        public ActionResult Update(int id)
        {
            var data = context.Categories.FirstOrDefault(x => x.CategoryId == id);
            return View("Add", data);
        }

        public void Delete(int id)
        {
            var data = context.Categories.FirstOrDefault(x => x.CategoryId == id);
            context.Categories.Remove(data);
            context.SaveChanges();
        }
    }
}

YakupMyBlog/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YakupMyBlog.Models;

namespace YakupMyBlog.Controllers
{
    public class TagController : Controller
    {
        Context context = new Context();
        // GET: Tag
        public ActionResult Index(int id)
        {
            return View(id);
        }

        public PartialViewResult TagWidget()
        {
            var data = context.Tags.ToList();
            return PartialView(data);
        }

        public ActionResult BlogList(int id)
        {
            //var data = context.Blogs.Where(x => x.Tags.Any(y => y.TagId == id)).ToList();
            var data = context.Blogs.Where(x => x.BlogTags.Any(y => y.TagID == id)).ToList();
            return View("BlogListWidget", data);
        }

        public ActionResult TagList()
        {
            var data = context.Tags.ToList();
            return View(data);
        }

        public ActionResult Add()
        {
            Tag tag = new Tag();
            return View(tag);
        }

        [HttpPost]
        public ActionResult Add(Tag tag)
        {
            context.Tags.AddOrUpdate(tag);
            context.SaveChanges();
            return RedirectToAction("TagList");
        }

        public ActionResult Update(int id)
        {
            var data = context.Tags.FirstOrDefault(x => x.TagId == id);
            return View("Add", data);
        }

        public void Delete(int id)
        {
            var data = context.Tags.FirstOrDefault(x => x.TagId == id);
            context.Tags.Remove(data);
            context.SaveChanges();
        }
    }
}

YakupMyBlog/Views/Shared/BlogListWidget.cshtml
@{ 
    Layout = null;
}
@model IEnumerable<YakupMyBlog.Models.Blog>

@helper ShortContent(string content)
{
    if (content.Length > 300)
    {
        @content.Substring(0, 300)
    }
    else
    {
        @content
    }
}
<div class="blog-posts col-blog">
    @foreach (YakupMyBlog.Models.Blog blog in Model)
    {
        <div class="post row">
            <div class="col-sm-4">
                <figure>
                    <a href="/Blog/BlogDetail/@blog.BlogId">
                        <div class="text-overlay">
                            <div class="info"><span>Hepsini Oku...</span></div>
                        </div>
                        @*<img src="@blog.Images.FirstOrDefault(x=>x.BlogID==blog.BlogId).MediumSize" alt="" />*@
                    <img src="@blog.Images.OrderByDescending(x=>x.ImageId).FirstOrDefault(y=>y.BlogID==blog.BlogId).MediumSize"  alt="" />
                        
                    </a>
                </figure>
            </div>
            <div class="col-sm-8 post-content">
                <div class="meta"><span class="date"></span>@blog.UploadDate <span class="comments"><a href="#">@blog.Comments.Count <i class="icon-chat-1"></i></a></span></div>
                <h2 class="post-title"><a href="/Blog/BlogDetail/@blog.BlogId">@blog.Title</a></h2>
                <p>@ShortContent(blog.Content)</p>
            </div>
        </div>
    }


</div>

YakupMyBlog/Views/Shared/SearchWidget.cshtml
<div class="sidebox widget">
    <h3 class="widget-title section-title">Ara</h3>
    <form class="searchform" action="/Home/Search" method="get">
        <label><i class="icon-search"></i></label>
        <input type="text" id="s2" name="search" placeholder="Ara Belki Bulasın" />
        <button type="submit" class="btn">Bul</button>
    </form>
</div>

YakupMyBlog/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="~/Content/Images/ladder.png">
    
    @*<link rel="shortcut icon" href="/Content/style/images/favicon.png">*@
    <title>@ViewBag.Title</title>
    <!-- Bootstrap core CSS -->
    <link href="/Content/style/css/bootstrap.min.css" rel="stylesheet">
    <link href="/Content/style/css/plugins.css" rel="stylesheet">
    <link href="/Content/style.css" rel="stylesheet">
    <link href="/Content/style/css/color/red.css" rel="stylesheet">
    <link href="/Content/style/type/bebas.css" rel="stylesheet">
    <link href="/Content/style/type/fontello.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
          <script src="style/js/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
          <![endif]-->
</head>
<body>
    <div id="preloader"><div id="status"><div class="spinner"></div></div></div>
    <div class="body-wrapper">
        <div class="navbar default">
            <div class="navbar-header">
                <div class="container">
                    <div class="basic-wrapper">
                        <a class="btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse"><i></i></a>
                        <div class="navbar-brand"><a href="index.html"><img src="/Content/style/images/logo.png" alt="" data-src="/Content/style/images/logo.png" data-ret="style/images/logo@2x.png" class="retina" /></a></div>
                        
                    </div>

                    <nav class="collapse navbar-collapse pull-right">
                        <ul class="nav navbar-nav">
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="current dropdown">
                                    <a href="#" class="dropdown-toggle js-activated">Admin Paneli</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="/Blog/BlogList">Blog Islemleri</a></li>
                                        <li><a href="/Category/CategoryList">Kategori Islemleri</a></li>
                                        <li><a href="/Tag/TagList">Etiket Islemleri</a></li>
                                        <li><a href="/Comment/CommentList">Yorum Islemleri</a></li>

                                    </ul>
                                </li>
                            }

                            <li><a href="/Home/Index">Anasayfa</a></li>
                            <li><a href="#">Who Am I ?</a></li>
                            <li><a href="#">Iletisim</a></li>
                            @if (User.IsInRole("Admin"))
                            {
                                <li><a href="/Security/Logout">Cikis Yap</a></li>
                            }
                            else
                            {
                                <li><a href="/Security/Login">Giris Yap</a></li>
                            }


                            <li class="dropdown social-dropdown pull-right">
                                <div class="share btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="icon-heart-1"></i></div>
                                <ul class="button-group dropdown-menu dropdown-menu-right share-links">
                                    <li><a href="#" class="btn"><i class="icon-s-facebook"></i></a></li>
                                    <li><a href="#" class="btn"><i class="icon-s-twitter"></i></a></li>
                                    <li><a href="#" class="btn"><i class="icon-s-instagram"></i></a></li>
                                </ul>
                            </li>
                            <!--/social-dropdown -->
                        </ul>
                        <!--/.navbar-nav -->
                    </nav>
                    <!--/.nav-collapse -->
                </div>
                <!--/.container -->
            </div>
            <!--/.navbar-header -->
        </div>
        <!--/.navbar -->
        <div class="offset"></div>
        <div class="dark-wrapper page-title">
            <div class="container inner">
                <h1> Yakup'un Merdiveni </h1>
            </div>
            <!--/.container -->
        </div>
        <!--/.page-title -->

        <div class="container inner">
            <div class="row">
                <div class="col-sm-8 content">
                    @RenderBody()
                    <!-- /.blog-posts -->

                    <div class="pagination">
                        <ul>
                            <li><a href="#" class="btn">Prev</a></li>
                            <li class="active"><a href="#" class="btn"><span>1</span></a></li>
                            <li><a href="#" class="btn"><span>2</span></a></li>
                            <li><a href="#" class="btn"><span>3</span></a></li>
                            <li><a href="#" class="btn">Next</a></li>
                        </ul>
                    </div>
                    <!-- /.pagination -->

                </div>
                <!-- /.content -->
                <aside class="col-sm-4 sidebar lp30">
                    @{ 
                        Html.RenderPartial("SearchWidget");
                    }
                    @{ 
                        Html.RenderAction("LastBlogsListWidget", "Home");
                    }
                    
                    
                    @{ 
                        Html.RenderAction("CategoryWidget", "Category");
                    }
                    
                    @{ 
                        Html.RenderAction("TagWidget", "Tag");
                    }
                   
                </aside>
                <!-- /.col-sm-4 .sidebar -->

            </div>
            <!-- /.row -->
        </div>
        <!--/.container -->
        <footer class="footer black-wrapper">
            <div class="container inner">
                <div class="row">

                    <div class="col-sm-3">
                        <div class="widget">
                            <h3 class="widget-title">Popular Posts</h3>
                            <ul class="post-list">
                                <li>
                                    <div class="icon-overlay"> <a href="blog-post.html"><img src="/Content/style/images/art/a1.jpg" alt="" /> </a> </div>
                                    <div class="meta">
                                        <h5><a href="blog-post.html">Magna Mollis Ultricies</a></h5>
                                        <em>3th Oct 2012 <span class="comments"><a href="#">8 <i class="icon-chat-1"></i></a></span></em>
                                    </div>
                                </li>
                                <li>
                                    <div class="icon-overlay"> <a href="blog-post.html"><img src="/Content/style/images/art/a2.jpg" alt="" /> </a> </div>
                                    <div class="meta">
                                        <h5><a href="blog-post.html">Ornare Nullam Risus</a></h5>
                                        <em>28th Sep 2012 <span class="comments"><a href="#">5 <i class="icon-chat-1"></i></a></span></em>
                                    </div>
                                </li>
                                <li>
                                    <div class="icon-overlay"> <a href="blog-post.html"><img src="/Content/style/images/art/a3.jpg" alt="" /> </a> </div>
                                    <div class="meta">
                                        <h5><a href="blog-post.html">Euismod Nullam</a></h5>
                                        <em>15th Aug 2012 <span class="comments"><a href="#">9 <i class="icon-chat-1"></i></a></span></em>
                                    </div>
                                </li>
                            </ul>
                            <!-- /.post-list -->
                        </div>
                        <!-- /.widget -->
                    </div>
                    <!-- /column -->

                    <div class="col-sm-3">
                        <div class="widget">
                            <h3 class="widget-title">About Us</h3>
                            <p>Aenean lacinia bibendum nulla sed leo posuere erat a ante venenatis dapibus posuere velit aliquet. Donec ullamcorper metus auctor fringi. Nullam quis risus. </p>
                            <p>Vestibulum id ligula porta  euismod semper. Maecenas faucibus mollis.</p>
                            <div class="divide5"></div>
                            <ul class="social">
                                <li><a href="#"><i class="icon-s-rss"></i></a></li>
                                <li><a href="#"><i class="icon-s-twitter"></i></a></li>
                                <li><a href="#"><i class="icon-s-facebook"></i></a></li>
                                <li><a href="#"><i class="icon-s-pinterest"></i></a></li>
                                <li><a href="#"><i class="icon-s-linkedin"></i></a></li>
                            </ul>
                        </div>
                        <!-- /.widget -->
                    </div>
                    <!-- /column -->

                    <div class="col-sm-3">
                        <div class="widget">
                            <h3 class="widget-title">Get In Touch</h3>
                            <p>Fusce dapibus, tellus commodo, tortor mauris condimentum utellus fermentum, porta sem malesuada magna. Sed posuere consectetur est at lobortis.</p>
                            <div class="contact-info">
                                <i class="icon-location"></i> Moonshine St. 14/05 Light City <br />
                                <i class="icon-phone"></i>+00 (123) 456 78 90 <br />
                                <i class="icon-mobile"></i>+80 (547) 455 47 54 <br />
                                <i class="icon-mail"></i> <a href="first.last%40email.html">first.last@email.com</a>
                            </div>
                        </div>
                    </div>
                    <!-- /column -->

                    <div class="col-sm-3">
                        <div class="widget">
                            <h4 class="widget-title">Tags</h4>
                            <ul class="tag-list">
                                <li><a href="#">Web</a></li>
                                <li><a href="#">Photography</a></li>
                                <li><a href="#">Illustation</a></li>
                                <li><a href="#">Fun</a></li>
                                <li><a href="#">Blog</a></li>
                            </ul>
                            <!-- /.tag-list -->
                        </div>
                        <!-- /.widget -->

                        <div class="widget">
                            <h4 class="widget-title">Categories</h4>
                            <ul class="circled">
                                <li><a href="#">Web Design (21)</a></li>
                                <li><a href="#">Photography (19)</a></li>
                                <li><a href="#">Graphic Design (16)</a></li>
                            </ul>
                        </div>
                        <!-- /.widget -->

                    </div>
                    <!-- /column -->

                </div>
                <!-- /.row -->
            </div>
            <!-- .container -->

            <div class="sub-footer">
                <div class="container">
                    <p class="pull-left">© 2015 Keepsake. All rights reserved. Theme by <a href="http://elemisfreebies.com/">elemis</a>.</p>
                    <ul class="footer-menu pull-right">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Portfolio</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
            </div>
        </footer>
        <!-- /footer -->
    </div>
    <!--/.body-wrapper -->
    <script src="/Content/style/js/jquery.min.js"></script>
    <script src="/Content/style/js/bootstrap.min.js"></script>
    <script src="/Content/style/js/plugins.js"></script>
    <script src="/Content/style/js/scripts.js"></script>
    @RenderSection("scripts", false);
</body>
</html>